kind = "mobile"
previewPath = "/"
title = "MediLembrete"
version = "1.0.0"
id = "artifacts/medilembrete"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 26271

[services.development]
run = "pnpm --filter @workspace/medilembrete run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/medilembrete", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/medilembrete", "run", "serve" ]

[services.env]
PORT = "26271"
BASE_PATH = "/"
